<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-RedBus.Worker-b164523b-08ca-4900-8ef3-8faee6c757ca</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="QuestPDF" Version="2024.12.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RedBus.Shared\RedBus.Shared.csproj" />
  </ItemGroup>
</Project>
